# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    key      = "terraform/wh-infra/terraform-aws-foundation-wh-infra.tfstate"
    region   = "ap-southeast-2"
    role_arn = "arn:aws:iam::007391679308:role/ga-aws-ausseabed-dev-terraform"
    bucket   = "ausseabed-terraform-all"
  }
}
