# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    role_arn = "arn:aws:iam::007391679308:role/ga-aws-ausseabed-dev-terraform"
    bucket   = "ausseabed-terraform-all"
    key      = "terraform/processing-pipeline-infra/processing-pipeline-infra.tfstate"
    region   = "ap-southeast-2"
  }
}
